<a href="https://colab.research.google.com/github/zemingzhang1/CSE574LECC-Intro-Machine-Learning/blob/main/Assignment%200/Final_spring23_assignment0(4).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<div align="center"> <h3><font color='cyan'>CSE 4/574 Sections A&C&D: Introduction to Machine Learning, Spring 2023 </font> 
<h1> Assignment 0 - Python Intro

<h3>Checkpoint: February 9, Thursday, 11:59pm
<h2><font color='red'>Final Due Date: </font> February 16, Thu, 11:59pm</div>

Welcome to your first CSE 574 assignment! The goal of this assignment is to sharpen your programming skills needed for this class. It is focused on familiarizing yourself with Python and main data science libraries that will be used for other assignments as well.

There are a total of five parts. We will focus on basic Python functions, explore numpy, pandas and matplotlib libraries, sci-kit learning and analyze the real-world dataset.

If you are new to Python, check our [Python resources page](https://ubuffalo-my.sharepoint.com/:w:/g/personal/avereshc_buffalo_edu/ESoUg6v6aoJImaeWXy90SqMBiubxGGAkG7dhaNyhuBum_w?e=3Tlwbz) and our class demos.


### Submission

All the details you need for this assignment are located within this notebook. You are expected to follow every block and complete the task within the marks ``` # BEGIN_YOUR_CODE ``` and ```# END_YOUR_CODE```. Do not modify or edit code beyond these lines. You can add helper functions in the new cells, if needed. We recommend completing the task within this .ipynb notebook, if needed you can convert it and submit as .py script. Try to make your code as clean and simple as possible and be sure to write your answers between the begin answer and end answer comments.

1. Submit at **UBLearns > Assignments**
2. The code of your implementations should be written in Python
3. All project files should be packed in a ZIP file named YOUR_FIRST_NAME_YOUR_LAST_NAME_assignment0.zip (e.g. alina_vereshchaka_assignment0.zip).
4. Your Jupyter notebook should be saved with the results. If you are submitting python scripts, after extracting the ZIP file and executing command python main.py in the first level directory, all the generated results and plots you used in your report should appear printed out in a clear manner.  
6. Include all the references that have been used to complete the assignment at the end of the submittion.

### Checkpoint Submission <font color='red'>[Due Date: Feb 9]</font>
Complete Part 1, Part 2 and Part 3 and submit the .ipynb with the saved output in the ZIP file named YOUR_FIRST_NAME_YOUR_LAST_NAME_assignment0_checkpoint.zip. Checkpoint will be evaluated after the final submission.

### Final Submission <font color='red'>[Due Date: Feb 16]</font>
Complete all parts of the assignment and submit the code in the ZIP file named YOUR_FIRST_NAME_YOUR_LAST_NAME_assignment0_final.zip. You may add slight modification to your Checkpoint submission if needed.

**Assignment Outline**

| Part | Description | # of tasks | Points |
| --- | --- | --- | --- |
| [Part 1](#part1) | Basics, Numpy Basics | 19 | 20 |
| [Part 2](#part2) | Algorithms | 2 | 20 |
| [Part 3](#part3) | Pandas Basics | 7 | 20 |
| [Part 4](#part4) | Matplotlib Basics | 8 | 20 |
| [Part 5](#part5) | Sci-kit Learning Basics | 3 | 20 |

    
### Academic Integrity

This assignment must be completed individually.
The standing policy of the Department is that all students involved in any academic integrity violation (e.g. plagiarism in any way, shape, or form) will receive an F grade for the course. The catalog describes plagiarism as “Copying or receiving material from any source and submitting that material as one’s own, without acknowledging and citing the particular debts to the source, or in any other manner representing the work of another as one’s own.”. Refer to the [Office of Academic Integrity](https://www.buffalo.edu/academic-integrity.html) for more details.


### Late Days Policy
You can use up to 7 late days throughout the course toward any assignments' checkpoint or final submission. You do not have to inform the instructor, as the late submission will be tracked in UBlearns.

### FAQ
>What does 'raise Exception("Not implemented yet")' mean?

Here we define a custom exception to highlight that the task is not implemented yet. Once you implement your code, ensure to remove this part.

>Can I add code beyond # BEGIN_YOUR_CODE parts.

Yes, you can add helper functions. Add them in the separate cell with the comments, why you need it


<a id='part1'></a>
## Part 1 - Python and Numpy Basics [20 points]

The first part of this assignment gives you practice with python syntax. Follow the cells below for the instructions.

In [70]:
''' Adding elements to a list during the runtime
Create an empty list and add five of your favourite holiday destinations to the list during the runtime using functions input() and append()
Print out the list.

'''

# BEGIN_YOUR_CODE
destinations = []

for i in range(1,6):
  destinations.append(input(f"Add favorite holiday destination {i}: "))

print("Personal list of favorite holiday destinations:")
for d in destinations:
  print(d)
# END_YOUR_CODE

Add favorite holiday destination 1: Austin
Add favorite holiday destination 2: Seattle
Add favorite holiday destination 3: San Francisco
Add favorite holiday destination 4: New York
Add favorite holiday destination 5: Denver
Personal list of favorite holiday destinations:
Austin
Seattle
San Francisco
New York
Denver


In [71]:
''' Updating elements
Given a string my_list, update the third element to 10 and sixth element to 25, so the output is as follows: [0, 5, 10, 15, 20, 25]
Print out the updated list.
'''

my_list = [0, 5, 'ten', 15, 20, 'twenty five']

# BEGIN_YOUR_CODE
my_list[2] = 10
my_list[5] = 25
my_list
# END_YOUR_CODE

[0, 5, 10, 15, 20, 25]

In [72]:
'''Write a program to find a total number of "the" in the sentence "the theatrics of neither these nor those" using regular expressions.
  Return the total number of "the"
'''

sentence = "the theatrics of neither these nor those"

# BEGIN_YOUR_CODE
from re import *

count = len(findall(r'\bthe\b', sentence))
f"There are {count} 'the' in the sentence."
# END_YOUR_CODE

"There are 1 'the' in the sentence."

In [73]:
''' Pattern
Write a function that will print the following pattern:
1
2 4
3 6 9
4 8 12 16
5 10 15 20 25
6 12 18 24 30 36

Only submissions with a written function that will encode this pattern will be considered for evaluation
'''

# BEGIN_YOUR_CODE
def pattern():
  for x in range(1, 7):
    for y in range(1, x+1):
      print(x*y, end=" ")
    print("")

pattern()
# END_YOUR_CODE

1 
2 4 
3 6 9 
4 8 12 16 
5 10 15 20 25 
6 12 18 24 30 36 


In [74]:
''' Reversing
Reverse the order of elements in a list given below, so the output is as follows: ['Avengers', 'Age of Ultron', 'Infinity War', 'Endgame']
Print the reversed list.
'''

list1 = ["Endgame", "Infinity War", "Age of Ultron", "Avengers"]

# BEGIN_YOUR_CODE
list1.reverse()
list1
# END_YOUR_CODE

['Avengers', 'Age of Ultron', 'Infinity War', 'Endgame']

In [75]:
'''Numbering a list
Write a function that will return a numbered list of the famous actors whose name starts from 'C' using "enumerate()" function.
'''

actors = ['Robert Downey Jr.', 'Scarlett Johansson', 'Chris Evans', 'Chris Hemsworth', 'Mark Ruffalo']

# BEGIN_YOUR_CODE
def number_list(actors):
  return [(idx+1, actor) for idx, actor in enumerate(actors) if actor.split(" ")[0] == "Chris"]

number_list(actors)
# END_YOUR_CODE

[(3, 'Chris Evans'), (4, 'Chris Hemsworth')]

In [76]:
'''Combining lists
Combine two lists given below using zip() function and print out the result
'''

actors = ['Robert Downey Jr.', 'Scarlett Johansson', 'Chris Evans', 'Chris Hemsworth', 'Mark Ruffalo']
role = ['Iron Man', 'Black Widow', 'Captain America', 'Thor', 'Hulk']

# BEGIN_YOUR_CODE
combined = list(zip(actors, role))
combined
# END_YOUR_CODE

[('Robert Downey Jr.', 'Iron Man'),
 ('Scarlett Johansson', 'Black Widow'),
 ('Chris Evans', 'Captain America'),
 ('Chris Hemsworth', 'Thor'),
 ('Mark Ruffalo', 'Hulk')]

In [171]:
''' Sum function
Modify the function below to return a sum of a and b
'''

def add(a: int, b: int) -> int:
  
  # BEGIN_YOUR_CODE
  return a+b
  raise Exception("Not implemented yet")
  # END_YOUR_CODE

We defined ```add_test``` to test your ```add``` function. For this function we ```import random``` library. This is a very commonly used package that helps to generate random values. For example:

``` python
random.randint(0, 100) #Returns any random integer from 0 to 100
```

In [172]:
import random

def add_test():
  a = random.randint(0, 9)
  b = random.randint(0, 9)
  result = add(a, b)

  return('Value of a is {0}, value of b is {1}, and their sum is {2}.'.format(a, b,result))

In [173]:
# Here we call our function 'add_test' to test your add function with random values
if __name__ == '__main__':
   print(add_test())

Value of a is 3, value of b is 3, and their sum is 6.


In this section we will explore one of the most commonly used package - Numpy. You can refer to the [Official NumPy Guide](https://numpy.org/doc/stable/).

In [80]:
'''Import the numpy package
'''

# BEGIN_YOUR_CODE
import numpy as np
# END_YOUR_CODE

In [81]:
''' Random integers
Create an array of random integers from 0 to 50 with the length 10 using numpy random generator.
Print the results.
'''

# BEGIN_YOUR_CODE
rand_array = np.random.randint(0, 51, 10)
rand_array
# END_YOUR_CODE

array([46, 43, 11, 28, 46, 27, 40,  5, 20, 43])

In [82]:
''' Slicing
Slice the above array and extract the first 2 elements, the last two elements, and all elements that are left in the middle.
'''

# BEGIN_YOUR_CODE
first_two = rand_array[:2]
last_two = rand_array[-2:]
middle = rand_array[2:-2]
# END_YOUR_CODE

print('The first 2 elements are {0} \nThe last two elements are {1} \nElements in the middle are {2}.'.format(first_two, last_two, middle))

The first 2 elements are [46 43] 
The last two elements are [20 43] 
Elements in the middle are [11 28 46 27 40  5].


In [83]:
'''Split an array
For the above list 'array' split the list into 5 equal parts  and print it in the form
[array([1,2]), array([3,4]), array([5,6]), array([7,8]), array([9,10])]

'''

# BEGIN_YOUR_CODE
array = np.array([1,2,3,4,5,6,7,8,9,10])
split_array = np.array_split(array, 5)

print('[{}]'.format(', '.join([str(a) for a in split_array])))
# END_YOUR_CODE

[[1 2], [3 4], [5 6], [7 8], [ 9 10]]


In [90]:
'''Generate two arrays of size 10 (integers randomly selected between 1 and 100). 
Print unique elements of array1 and common elements of both arrays separately
'''

# BEGIN_YOUR_CODE
array1 = np.random.randint(1, 100, 10)
array2 = np.random.randint(1, 100, 10)

unique_elements = np.setdiff1d(array1, array2)
common_elements = np.intersect1d(array1, array2)

print("Element of array1:", array1)
print("Element of array2:", array2)
print("Unique elements of array1:", unique_elements)
print("Common elements of both arrays:", common_elements)
# END_YOUR_CODE

Element of array1: [21  8 90 96 38 62 38 99 50 76]
Element of array2: [82 10 93 44 68 73 85 55 90 44]
Unique elements of array1: [ 8 21 38 50 62 76 96 99]
Common elements of both arrays: [90]


In [92]:
'''Changing dimensions
Convert your 1D array defined above to a 2D matrix and print its shape. The final output dimension should be 2x4.
'''

# BEGIN_YOUR_CODE
array = unique_elements.reshape(2, 4)

print("Original array shape:", unique_elements.shape)
print("new 2D matrix shape:", array.shape)
# END_YOUR_CODE

Original array shape: (8,)
new 2D matrix shape: (2, 4)


In [93]:
'''Changing dimensions
Convert a matrix below to 1D array and print its dimension
'''

A = np.array([[3,4], [5,6], [7,8]])

# BEGIN_YOUR_CODE
Ato1D = np.reshape(A, (1, -1))
f"The dimension of matrix A is {A.shape}", f"The dimension of the new 1D array from matrix A is {Ato1D.shape}"
# END_YOUR_CODE

('The dimension of matrix A is (3, 2)',
 'The dimension of the new 1D array from matrix A is (1, 6)')

In [94]:
''' Matrices
Create two matrices A and B of size 4X6 and 6X4 respectively with random values from 0 to 1, and perform the dot product on them
'''

# BEGIN_YOUR_CODE
A = np.random.rand(4,6)
B = np.random.rand(6,4)
dot_product = np.dot(A, B)
# END_YOUR_CODE

print('\nMatrix A is \n{0} \nMatrix B is \n{1}, \nTheir product is \n{2}'.format(A, B, dot_product))


Matrix A is 
[[0.112627   0.13976154 0.67586577 0.19428197 0.26566657 0.01623507]
 [0.15707257 0.55776434 0.21854345 0.70060564 0.5158252  0.45124723]
 [0.56650553 0.70023161 0.39172193 0.00500979 0.00544782 0.17123163]
 [0.02097878 0.10490447 0.17715259 0.59272633 0.1723836  0.9566835 ]] 
Matrix B is 
[[0.31936387 0.9111481  0.385952   0.30202913]
 [0.37663821 0.11200386 0.62326323 0.5706737 ]
 [0.68869876 0.21863316 0.62541886 0.92227388]
 [0.48640542 0.69280437 0.07939861 0.70357098]
 [0.42780542 0.03637729 0.00436702 0.65437503]
 [0.57378257 0.72090252 0.65240694 0.28458551]], 
Their product is 
[[0.77154525 0.4220079  0.58045381 1.05226521]
 [1.23111826 1.08282121 0.89721422 1.52618618]
 [0.8174509  0.80735277 1.0121971  0.98779952]
 [1.07919592 1.17618569 0.85623588 1.03167245]]


In [95]:
''' Multiply the Matrix A from previous question with a scalar 5 using multiply() function
'''

# BEGIN_YOUR_CODE
result = np.multiply(A, 5)
result
# END_YOUR_CODE

array([[0.56313499, 0.69880772, 3.37932886, 0.97140984, 1.32833286,
        0.08117533],
       [0.78536285, 2.78882168, 1.09271723, 3.50302822, 2.57912598,
        2.25623614],
       [2.83252765, 3.50115803, 1.95860963, 0.02504893, 0.02723909,
        0.85615814],
       [0.10489388, 0.52452233, 0.88576296, 2.96363165, 0.86191798,
        4.78341752]])

In [96]:
''' Maximum value
Return the maximum value in each row of Matrix A created in the previous question. 
Result should come in the form: [row1_max row2_max row3_max row4_max row5_max]
Print our the results
'''

# BEGIN_YOUR_CODE
result = np.amax(A, axis=1)
result
# END_YOUR_CODE

array([0.67586577, 0.70060564, 0.70023161, 0.9566835 ])

In [97]:
''' Element-wise multiplication
Define two matrices A (3X4) and B (3X4) with random values from 0 to 9. Perform element-wise multiplication of Matrices A and B
''' 

# BEGIN_YOUR_CODE
A = np.random.randint(0, 9, (3, 4))
B = np.random.randint(0, 9, (3, 4))
multiplication = np.multiply(A, B)
# END_YOUR_CODE

print('\nMatrix A is \n{0} \nMatrix B is \n{1}, \nTheir element-wise multiplication is \n{2}'.format(A, B, multiplication))


Matrix A is 
[[3 7 5 5]
 [1 4 3 3]
 [3 0 6 2]] 
Matrix B is 
[[0 5 5 6]
 [0 7 6 7]
 [5 6 1 4]], 
Their element-wise multiplication is 
[[ 0 35 25 30]
 [ 0 28 18 21]
 [15  0  6  8]]


<a id='part3'></a>
## Part 2 - Algorithms [30 points]

### Euclidian Distance

Let point $p$ have Cartesian coordinates $(p_1,p_2)$ and let point $q$ have coordinates $(q_1,q_2)$. Then the distance between $p$ and $q$ is given by:
    $d(p,q) = \sqrt{(q_1-p_1)^2 + (q_2-p_2)^2}$.</math>

In [174]:
''' Euclidean distance
Using numpy library return the Euclidean distance between two locations, where the locations are pairs of numbers (e.g., (3, 5)) '''

def euclidean_distance(loc1: int, loc2: int) -> float:
  # BEGIN_YOUR_CODE
  p1, p2 = loc1
  q1, q2 = loc2 
  return np.sqrt(np.square(q1 - p1) + np.square(q2 - p2))
  raise Exception("Not implemented yet")
  # END_YOUR_CODE

In [175]:
def euclidean_distance_test():
  random.seed(42)
  for _ in range(10):
      x1 = random.randint(0, 10)
      x2 = random.randint(0, 10)
      y1 = random.randint(0, 10)
      y2 = random.randint(0, 10)
      dist = euclidean_distance((x1, x2), (y1, y2))
  return('Loc1 is ({0}, {1}), loc2 is ({2}, {3}). Euclidian disctance is {4}.'.format(x1, x2, y1, y2, dist))

In [176]:
if __name__ == '__main__':
  print(euclidean_distance_test())

Loc1 is (3, 5), loc2 is (1, 1). Euclidian disctance is 4.47213595499958.


### String Operations

In [178]:
''' Alphabetically first word
Given a string, lowercase, sort out  all words in the alphabetical order and return the word that comes first.
If the input text is an empty string, return an empty string or throw an error. '''

def first_word(text: str) -> str:
    
  # BEGIN_YOUR_CODE
  text = text.split()
  words = [(w.lower(),idx) for idx, w in enumerate(text)]
  if not words:
      return ""
  retIdx = sorted(words, key = lambda x:x[0])[0][1]
  return text[retIdx]
  raise Exception("Not implemented yet")
  # END_YOUR_CODE

In [179]:
def first_word_test():
  result0 = first_word('WelCome tO Ub')
  result1 = first_word('CSE574 IntRo to ML cLasS')
  result2 = first_word('SequenCes of DeCiSions')
  result3 = first_word('Wolf, Panther, Leopard, Dog, Cat')
  return result0, result1, result2, result3

In [180]:
if __name__ == '__main__':
  print(first_word_test())

('tO', 'cLasS', 'DeCiSions', 'Cat')


## Load from Drive*

*If you are using Goolge Colab, uncomment the following piece of code and verify the file using the command, if you can see your file ```penguins.csv``` you are good to go.

In [181]:
!pwd
!ls

/content/drive/MyDrive
'1080p (1).mov'
 1080p.mov
 2-11.pdf
 360EAS.gdoc
'442 Meeting Notes.gdoc'
'Applicable course work.gdoc'
 ART250.gdoc
'ART250 PJ1.gdoc'
'Baudrillard’s Theory presented in his written scholarly article Simulacra and Simulation.gdoc'
'‘Beneatha’s Place’ adds to the conversation started by ‘Clybourne Park’ - The Washington Post.pdf'
'bio 200.gdoc'
'Chinese textbook.pdf'
'Colab Notebooks'
'Copy of W1-LEC-EX.drawio'
'cse191 notes .gdoc'
 CSE220.gdoc
'CSE220 - Line chart 1.gsheet'
 CSE331WH2.gdoc
 CSE365.gdoc
'CSE443 HW2.gdoc'
'CSE443 HW3.gdoc'
'Department_of_Computer_Science_and_Engineering (1).gslides'
 Department_of_Computer_Science_and_Engineering.gslides
 EAS360.pdf
'EAS503-lecture questions.gdoc'
 EAS508_Fall22_Lecture2.pdf
 eas508_fall22_lecture3.pdf
 eas508_fall22_lecture4.pdf
'EAS508 HW1.gdoc'
'Exam 2.gdoc'
 exported_2020-10-07_12-25-45.mp4
'Extra Credit Questions: Ze Ming Zhang.gdoc'
 Final.drawio
'final final.gslides'
 final.gslides
'Getting started.pdf'
'Gi

In [182]:
from google.colab import drive
drive.mount('/content/drive')
%cd ..
%cd /content/drive/MyDrive

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
/content/drive
/content/drive/MyDrive


<a id='part4'></a>
##  Part 3 - Pandas Basics [20 points]

Some important resources:

- [A Pandas guide](https://pandasguide.readthedocs.io/en/latest/) covers fundamental information about the package

- [Pandas Cheat Sheet](https://www.datacamp.com/community/blog/python-pandas-cheat-sheet)

### Penguin dataset
In this section we will explore with you Palmer Archipelago (Antarctica) penguin dataset. It contains three penguin species and includes measurements of bill length, bill depth, flipper length and body mass. Overall, we are provided with 344 data samples.
![image.png](attachment:image.png)

The dataset consists of 7 columns:
- species: penguin species (Chinstrap, Adélie, or Gentoo)
- culmen_length_mm: culmen length (mm)
- culmen_depth_mm: culmen depth (mm)
- flipper_length_mm: flipper length (mm)
- body_mass_g: body mass (g)
- island: island name (Dream, Torgersen, or Biscoe) in the Palmer Archipelago (Antarctica)
- sex: penguin sex (female, male)

#### What are culmen length & depth?
The culmen is "the upper ridge of a bird's beak"

#### What are flippers?
Penguins wings are called flippers. They are flat, thin, and broad with a long, tapered shape and a blunt, rounded tip.
 
![image.png](attachment:image-2.png)


In [183]:
'''Install and import pandas library
'''

# BEGIN_YOUR_CODE
import pandas as pd
# END_YOUR_CODE

In [184]:
'''Read given 'DataFile' and extract into Dataframe
'''

# BEGIN_YOUR_CODE
csvUrl = "https://raw.githubusercontent.com/zemingzhang1/CSE574LECC-Intro-Machine-Learning/main/Assignment%200/penguins.csv"
data = pd.read_csv(csvUrl)
data
# END_YOUR_CODE

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0       Adelie  Torgersen            39.1           18.7              181.0   
1       Adelie  Torgersen            39.5           17.4              186.0   
2       Adelie  Torgersen            40.3           18.0              195.0   
3       Adelie  Torgersen             NaN            NaN                NaN   
4       Adelie  Torgersen            36.7           19.3              193.0   
..         ...        ...             ...            ...                ...   
339  Chinstrap      Dream            55.8           19.8              207.0   
340  Chinstrap      Dream            43.5           18.1              202.0   
341  Chinstrap      Dream            49.6           18.2              193.0   
342  Chinstrap      Dream            50.8           19.0              210.0   
343  Chinstrap      Dream            50.2           18.7              198.0   

     body_mass_g     sex  year  
0         3750.0    male  2007  
1         3800.0  female  2007  
2         3250.0  female  2007  
3            NaN     NaN  2007  
4         3450.0  female  2007  
..           ...     ...   ...  
339       4000.0    male  2009  
340       3400.0  female  2009  
341       3775.0    male  2009  
342       4100.0    male  2009  
343       3775.0  female  2009  

[344 rows x 8 columns]

In [185]:
'''Provide the main statistics about the entries of the dataset (mean, std, etc.)
'''

# BEGIN_YOUR_CODE
from IPython.display import display

uniqueSpecies= set(data["species"])
for i in uniqueSpecies:
  print(f"Entries of {i} species summary")
  display(data[data["species"]==i].describe())
  print("\n")
summary  = data.describe()

print("Total data summary")
summary
# END_YOUR_CODE

Entries of Chinstrap species summary


bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g  \
count       68.000000      68.000000          68.000000    68.000000   
mean        48.833824      18.420588         195.823529  3733.088235   
std          3.339256       1.135395           7.131894   384.335081   
min         40.900000      16.400000         178.000000  2700.000000   
25%         46.350000      17.500000         191.000000  3487.500000   
50%         49.550000      18.450000         196.000000  3700.000000   
75%         51.075000      19.400000         201.000000  3950.000000   
max         58.000000      20.800000         212.000000  4800.000000   

              year  
count    68.000000  
mean   2007.970588  
std       0.863360  
min    2007.000000  
25%    2007.000000  
50%    2008.000000  
75%    2009.000000  
max    2009.000000



Entries of Gentoo species summary


bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g  \
count      123.000000     123.000000         123.000000   123.000000   
mean        47.504878      14.982114         217.186992  5076.016260   
std          3.081857       0.981220           6.484976   504.116237   
min         40.900000      13.100000         203.000000  3950.000000   
25%         45.300000      14.200000         212.000000  4700.000000   
50%         47.300000      15.000000         216.000000  5000.000000   
75%         49.550000      15.700000         221.000000  5500.000000   
max         59.600000      17.300000         231.000000  6300.000000   

              year  
count   124.000000  
mean   2008.080645  
std       0.792206  
min    2007.000000  
25%    2007.000000  
50%    2008.000000  
75%    2009.000000  
max    2009.000000



Entries of Adelie species summary


bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g  \
count      151.000000     151.000000         151.000000   151.000000   
mean        38.791391      18.346358         189.953642  3700.662252   
std          2.663405       1.216650           6.539457   458.566126   
min         32.100000      15.500000         172.000000  2850.000000   
25%         36.750000      17.500000         186.000000  3350.000000   
50%         38.800000      18.400000         190.000000  3700.000000   
75%         40.750000      19.000000         195.000000  4000.000000   
max         46.000000      21.500000         210.000000  4775.000000   

              year  
count   152.000000  
mean   2008.013158  
std       0.821780  
min    2007.000000  
25%    2007.000000  
50%    2008.000000  
75%    2009.000000  
max    2009.000000



Total data summary


bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g  \
count      342.000000     342.000000         342.000000   342.000000   
mean        43.921930      17.151170         200.915205  4201.754386   
std          5.459584       1.974793          14.061714   801.954536   
min         32.100000      13.100000         172.000000  2700.000000   
25%         39.225000      15.600000         190.000000  3550.000000   
50%         44.450000      17.300000         197.000000  4050.000000   
75%         48.500000      18.700000         213.000000  4750.000000   
max         59.600000      21.500000         231.000000  6300.000000   

              year  
count   344.000000  
mean   2008.029070  
std       0.818356  
min    2007.000000  
25%    2007.000000  
50%    2008.000000  
75%    2009.000000  
max    2009.000000

In [186]:
''' Print shape of the dataset '''

# BEGIN_YOUR_CODE
dataSp = data.shape
dataSp
# END_YOUR_CODE

(344, 8)

In [187]:
''' Return all the column names'''

# BEGIN_YOUR_CODE
columns = list(data.columns)
columns
# END_YOUR_CODE

['species',
 'island',
 'bill_length_mm',
 'bill_depth_mm',
 'flipper_length_mm',
 'body_mass_g',
 'sex',
 'year']

In [188]:
''' Print a list of penguin species '''

# BEGIN_YOUR_CODE
speciesList = list(data["species"])
speciesSet = set(list(data["species"]))
speciesList,speciesSet
# END_YOUR_CODE

(['Adelie',
  'Adelie',
  'Adelie',
  'Adelie',
  'Adelie',
  'Adelie',
  'Adelie',
  'Adelie',
  'Adelie',
  'Adelie',
  'Adelie',
  'Adelie',
  'Adelie',
  'Adelie',
  'Adelie',
  'Adelie',
  'Adelie',
  'Adelie',
  'Adelie',
  'Adelie',
  'Adelie',
  'Adelie',
  'Adelie',
  'Adelie',
  'Adelie',
  'Adelie',
  'Adelie',
  'Adelie',
  'Adelie',
  'Adelie',
  'Adelie',
  'Adelie',
  'Adelie',
  'Adelie',
  'Adelie',
  'Adelie',
  'Adelie',
  'Adelie',
  'Adelie',
  'Adelie',
  'Adelie',
  'Adelie',
  'Adelie',
  'Adelie',
  'Adelie',
  'Adelie',
  'Adelie',
  'Adelie',
  'Adelie',
  'Adelie',
  'Adelie',
  'Adelie',
  'Adelie',
  'Adelie',
  'Adelie',
  'Adelie',
  'Adelie',
  'Adelie',
  'Adelie',
  'Adelie',
  'Adelie',
  'Adelie',
  'Adelie',
  'Adelie',
  'Adelie',
  'Adelie',
  'Adelie',
  'Adelie',
  'Adelie',
  'Adelie',
  'Adelie',
  'Adelie',
  'Adelie',
  'Adelie',
  'Adelie',
  'Adelie',
  'Adelie',
  'Adelie',
  'Adelie',
  'Adelie',
  'Adelie',
  'Adelie',
  'Adelie',
  'A

In [189]:
'''Print top 10 rows of the dataset'''

# BEGIN_YOUR_CODE
topTen = data.head(10)
topTen
# END_YOUR_CODE

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen            39.1           18.7              181.0   
1  Adelie  Torgersen            39.5           17.4              186.0   
2  Adelie  Torgersen            40.3           18.0              195.0   
3  Adelie  Torgersen             NaN            NaN                NaN   
4  Adelie  Torgersen            36.7           19.3              193.0   
5  Adelie  Torgersen            39.3           20.6              190.0   
6  Adelie  Torgersen            38.9           17.8              181.0   
7  Adelie  Torgersen            39.2           19.6              195.0   
8  Adelie  Torgersen            34.1           18.1              193.0   
9  Adelie  Torgersen            42.0           20.2              190.0   

   body_mass_g     sex  year  
0       3750.0    male  2007  
1       3800.0  female  2007  
2       3250.0  female  2007  
3          NaN     NaN  2007  
4       3450.0  female  2007  
5       3650.0    male  2007  
6       3625.0  female  2007  
7       4675.0    male  2007  
8       3475.0     NaN  2007  
9       4250.0     NaN  2007

<a id='part5'></a>
## Part 4 - Matplotlib Basics [20 points]

Heatmaps is a useful plot tool which help us visualize the data density or distribution. Refer the below documentation for more details on heatmap.

[Matplotlib tutorial](https://machinelearningknowledge.ai/matplotlib-heatmap-complete-tutorial-for-beginners/)

**Note:** You can only use matplotlib library for the following tasks

In [ ]:
''' Install and import matplotlib library
'''

# BEGIN_YOUR_CODE

# END_YOUR_CODE

In [ ]:
''' Heatmap
Take any random numpy array of dimension 12x15 and plot a heatmap
'''

# BEGIN YOUR CODE

# END YOUR CODE

In [ ]:
'''For the given value x plot the function y = 1/x using list comprehension on y.
You can check https://docs.python.org/3/tutorial/datastructures.html#list-comprehensions to learn how to use list comprehension
'''

x = range(1,26)

# BEGIN YOUR CODE

# END YOUR CODE

In [ ]:
'''For the given value x plot the function y = x^3 using lambda function y.

Lambda function is a small anonymous function which consist of a single expression, and is usually used when we need the function for a smaller duration
https://realpython.com/python-lambda/
'''

x = range(25)

# BEGIN YOUR CODE

# END YOUR CODE


In [ ]:
'''On one graph draw two lines:
1) Plot the function y = x^3 using lambda function y (use your code from above)
2) A scatter plot for y = x^4 using either list comprehension or lambda function for evaluating y
'''

x = range(25)

# BEGIN YOUR CODE

# END YOUR CODE

In [ ]:
'''Create subplots showing graphs of tan and cot side by side of each other
the value of theta ranges from -60 to 60

HINT: You might want to utilize np.linspace() or np.arrange() to create smooth curves
'''

import math

# BEGIN YOUR CODE

# END YOUR CODE

In [ ]:
''' Penguin ("penguin.csv"): total number of penguins per Species
Plot a graph which shows the total number of penguins per species
'''

# BEGIN YOUR CODE

# END YOUR CODE

In [ ]:
''' Penguin ("penguin.csv"): total number of penguins between range of body mass
Plot a graph which shows the total number of penguins having body_mass_g between 3200 and 4500
'''

# BEGIN YOUR CODE

# END YOUR CODE

#### Results analyzing

Analyze the graph and answer the following two questions:

**1) What is your inference from the above graph?**

*YOUR ANSWER:*

**2) Which species has the most number of penguins having body_mass_g between 3200 and 4500?**

*YOUR ANSWER:*

**3) Which is the most common species of penguins?**

*YOUR ANSWER:*


# Part 5 - Sckit-learn Basics

Skit-learn is a commonly used data analysis library. It contains in-build unsupervised and supervised learning algorithms. Check more details here - https://scikit-learn.org/stable/
In this part we will use 

In [ ]:
'''Install and import scikit-learn library
'''

# BEGIN_YOUR_CODE

# END_YOUR_CODE

In [ ]:
''' Prepare Penguins dataset for training
    Define our X_data = all the columns, exept 'Species'. You can use drop() function
    Define Y_target = 'Species' column from the dataset
    Using train_test_split function divide the dataset into training and testing as 80/20. 
'''

# BEGIN_YOUR_CODE

# END_YOUR_CODE

In [ ]:
''' Fit the model
    Create and fit a logistic regression model to predict the 'Species' of a penguin using all of the other features in the dataset.
    You can use one hot encoding to encode categorical-based feature ('island' and 'sex').
    You can read more about the inbuild Logistic Regression model here - https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html
    Return the accuracy_score of your prediction and parameter values
'''

# BEGIN_YOUR_CODE
    
# END_YOUR_CODE

## References Used

**List below all the references you used to complete this assignment**